### PR TITLE
Added plane functionality

### PR DESCRIPTION
**Pull request by jordanhowe25**
Added loop for generating planes during game.  Added plane animation and ability to create planes.  Added a function to get a random integer between a range.

### CODE REVIEW

**Review by richardlara67 — COMMENTED** [review]
Awesome job, Jordan. I tested your code and it seems that the user is also able to pop the airplane. The question is- should we call that a bug or a feature?

**Comment by jordanhowe25** [comment]
That functionality was already there, I just uncommented it.  Easy to remove if that's what we want.  There is a small bug that I need to look at and that is the condition that stops the object moving when off screen... it just keeps going like the energy bunny.  Minor and not noticeable unless you watch the output, after the game resets its cleaned up at least.  I wasn't quite sure what we were doing with the plane but I can make it do whatever.  I might look into scaling the image down just a little.

**Comment by richardlara67** [comment]
As per client:
> This is a great game idea. We'd also like to incorporate store logos. It could be something similar to the Shop Drop game with a flying plane across the sky. This could be part of the game play as well. 

This is the only reason why we want to have a plane flying across the screen. It’s mostly for marketing purposes.

**Comment by jordanhowe25** [comment]
Ok, makes sense.  It wouldnt be too good to crash the plane being the environment we are in.  So I'll remove the poppable effect.  We will need to add new features such as a new plane model or modified plane model that will hold the logo.  Probably like a legit airliner or somethin instead of the propeller model.  Need to make sure it stays in the background so it doesnt cover balloons that are high up to make they are still poppable.  Need a list of stores to obtain logos to apply.

**Pull request merged**
